// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  experience: dynamic(() => import("./Experience")),
  image_block: dynamic(() => import("./ImageBlock")),
  my_hero: dynamic(() => import("./MyHero")),
  tech_list: dynamic(() => import("./TechList")),
  text_fild: dynamic(() => import("./TextFild")),
};
